### ISSUE TITLE
반응형 적용

### ISSUE THREAD

**Issue by teamsmiley** [designerjustinlee/project_AFK#4]
![image](https://user-images.githubusercontent.com/4934139/117401733-fb1b8680-aeb9-11eb-841b-647b960ab523.png)

**Comment by teamsmiley** [comment]
![Image 2021-05-06 22-25-44](https://user-images.githubusercontent.com/4934139/117401860-2d2ce880-aeba-11eb-8ea9-7ad8adadeac0.png)

**Comment by teamsmiley** [comment]
e14917cb

**Comment by teamsmiley** [comment]
![image](https://user-images.githubusercontent.com/4934139/117403692-703c8b00-aebd-11eb-8d88-b5eb3b8f9956.png)

**Comment by teamsmiley** [comment]
반응형 완료

**Comment by teamsmiley** [comment]
확인후 의견 달아주세요

**Comment by sjnoh3** [comment]
저도 개인적으로 버튼이 밑에 있는게 더 자연스러운것 같습니다~

**Comment by designerjustinlee** [comment]
아주 좋습니다!!
