### ISSUE TITLE
dark mode지원

### ISSUE THREAD

**Issue by teamsmiley** [designerjustinlee/project_AFK#5]
하얀색  흰바탕이 눈이 너무 아프다..

다크모드도 지원을 해볼가?

**Comment by teamsmiley** [comment]
e14917cb

**Comment by teamsmiley** [comment]
라이트모드 

![image](https://user-images.githubusercontent.com/4934139/117403777-9530fe00-aebd-11eb-8e37-e1e8de17fec0.png)


![image](https://user-images.githubusercontent.com/4934139/117403805-9eba6600-aebd-11eb-9914-a8e415735894.png)

![image](https://user-images.githubusercontent.com/4934139/117403834-ad088200-aebd-11eb-91f9-be0e34f57e62.png)

![image](https://user-images.githubusercontent.com/4934139/117403843-b1cd3600-aebd-11eb-978f-10e2af867c15.png)

**Comment by teamsmiley** [comment]
이미지는 반전을 해서 처리햇습니다. 

더 좋은 의견을 달아주세요

**Comment by sjnoh3** [comment]
제 눈에는 위 macOS의 다크모드가 조금 더 눈에 soft하게 들어오는데 가능할까요?? 캐릭터가 구름인것을 생각하면 파스텔톤 느낌의 어두운 색 (color code: 141414 혹은 1B1B1B) 그리고 밝은 색(color code: F3F3F3 혹은 E1E1E1)도 괜찮을것 같은데 어떻게들 생각하세요?

**Comment by designerjustinlee** [comment]
네 현재 비주얼 디자인 하고 있습니다. 점심 정도에 보여드릴께요 :)

**Comment by teamsmiley** [comment]
배경을 수정한 관계로 다크모드 필요가 없어졋음.

관련코드 삭제

**Comment by teamsmiley** [comment]
57162f7
