### ISSUE TITLE
클릭후 완료시 이미지가 이렇게 바귀는게 맞는것이겟죠?

### ISSUE THREAD

**Issue by teamsmiley** [designerjustinlee/project_AFK#6]
![image](https://user-images.githubusercontent.com/4934139/117403989-fbb61c00-aebd-11eb-82b9-70ade297777a.png)

**Comment by sjnoh3** [comment]
넵 그 라인 없애는것 했습니다 
Branch에 컴밋 해놓을게요! 
지금은 한번 extension이 active 된 순간을 기점으로 time lapse 트레킹 해서 30분 주기로 다시 active 시키는거 알아보고 있어요! ==> 이거 이해가 잘 안되요

**Comment by sjnoh3** [comment]
푸시 후 이슈 클로즈 하겠습니다

**Comment by teamsmiley** [comment]
이건 현재 익스텐션을 설치해보고 상황을 보고 이야기를 다시 나눠야할거같아요.. 오늘 될가요?

**Comment by designerjustinlee** [comment]
오후 5시 정도 괜찮으신가요??

**Comment by teamsmiley** [comment]
넵 저는 됩니다

전화주시죠
