### ISSUE TITLE
화면에 대한 제안

### ISSUE THREAD

**Issue by teamsmiley** [designerjustinlee/project_AFK#7]
![image](https://user-images.githubusercontent.com/4934139/117500160-17a6d580-af31-11eb-9851-83c551f9eb69.png)

일단 기능이 완성이 되었습니다. 

기본기능만 되면 되므로 일단 이정도로 마무리햇으면 합니다.

모래시게는 무지개로 바꾸신다고 하니 시간에 상관없이 class 만 주면 계속 움직이는 css를 만들어서 계속 애니메이션이 보이게 하는게 좋을거같아요.

count에서 done 이 되면 지금 이미지들 바꾸는게 그때 class를 제거해버리면 움직임 없는 css를 적용해버리면 될듯 보입니다...

어떻세요 ?

**Comment by designerjustinlee** [comment]
네 좋습니다!!!

**Comment by teamsmiley** [comment]
5시쯤에 주시면 제가 합쳐보겠습니다.

**Comment by designerjustinlee** [comment]
네네 그렇게 하겠습니다.
